,
    "conservatori": [
        "CONSERVATORIO di ADRIA (RO) \"Antonio Buzzolla\" http://www.conservatorioadria.it",
        "CONSERVATORIO di ALESSANDRIA \"Antonio Vivaldi\"	http://www.conservatoriovivaldi.it",
        "CONSERVATORIO di AVELLINO \"Domenico Cimarosa\"	http://www.conservatorio.avellino.it",
        "CONSERVATORIO di BARI \"Niccolò Piccinni\"	http://www.conservatoriopiccinni.it",
        "CONSERVATORIO di BENEVENTO \"Nicola Sala\"	http://www.conservatorionicolasala.eu/",
        "CONSERVATORIO di BOLOGNA \"Giovan B. Martini\"	http://www.conservatorio-bologna.com/",
        "CONSERVATORIO di BOLZANO \"Claudio Monteverdi\"	http://www.conservatoriobolzano.it",
        "CONSERVATORIO di BRESCIA \"Luca Marenzio\"	http://www.conservatorio.brescia.it",
        "CONSERVATORIO di BRESCIA \"Luca Marenzio\" - sezione staccata	http://www.conservatorio.brescia.it/darfo/",
        "CONSERVATORIO di CAGLIARI \"Pierluigi da Palestrina\"	http://www.conservatoriocagliari.it/",
        "CONSERVATORIO di CAMPOBASSO \"Lorenzo Perosi\"	http://www.conservatorioperosi.it",
        "CONSERVATORIO di CASTELFRANCO VENETO (TV) \"Agostino Steffani\"	http://www.steffani.it",
        "CONSERVATORIO di CESENA (FO) \"Bruno Maderna\"	http://www.conservatoriomaderna-cesena.it",
        "CONSERVATORIO di COMO \"Giuseppe Verdi\"	http://www.conservatoriocomo.it/",
        "CONSERVATORIO di COSENZA \"Stanislao Giacomantonio\"	http://www.conservatoriodicosenza.it/",
        "CONSERVATORIO di CUNEO \"G.F. Ghedini\"	http://www.conservatoriocuneo.it/",
        "CONSERVATORIO di FERMO (AP) \"Giovambattista Pergolesi\"	http://www.conservatorio.net",
        "CONSERVATORIO di FERRARA \"Girolamo Frescobaldi\"	http://www.conservatorioferrara.it",
        "CONSERVATORIO di FIRENZE \"Luigi Cherubini\"	http://www.conservatorio.firenze.it",
        "CONSERVATORIO di FOGGIA \"Umberto Giordano\"	http://www.conservatoriofoggia.it",
        "CONSERVATORIO di FOGGIA \"Umberto Giordano\" - sezione staccata	http://www.conservatoriorodi.it",
        "CONSERVATORIO di FROSINONE \"Licinio Refice\"	http://www.conservatorio-frosinone.it/",
        "CONSERVATORIO di GENOVA \"Nicolò Paganini\"	http://www.conservatoriopaganini.org/",
        "CONSERVATORIO di L'AQUILA \"Alfredo Casella\"	http://www.consaq.it",
        "CONSERVATORIO di LA SPEZIA \"Giacomo Puccini\"	http://www.conservatoriopuccini.com",
        "CONSERVATORIO di LATINA \"Ottorino Respighi\"	http://www.conservatorio.latina.it/",
        "CONSERVATORIO di LECCE \"Tito Schipa\"	http://www.conservatoriolecce.it",
        "CONSERVATORIO di LECCE \"Tito Schipa\" - sezione staccata	http://www.conservatoriolecce.it",
        "CONSERVATORIO di MANTOVA \"Lucio Campiani\"	http://www.conservatoriomantova.com",
        "CONSERVATORIO di MATERA \"Egidio R. Duni\"	http://www.conservatoriomatera.it",
        "CONSERVATORIO di MESSINA \"Arcangelo Corelli\"	http://www.conservatoriomessina.it",
        "CONSERVATORIO di MILANO \"Giuseppe Verdi\"	http://www.consmilano.it/",
        "CONSERVATORIO di MONOPOLI (BA) \"Nino Rota\"	http://www.conservatoriodimonopoli.org",
        "CONSERVATORIO di NAPOLI \"S. Pietro a Majella\"	http://www.sanpietroamajella.it/",
"CONSERVATORIO di NOVARA \"Guido Cantelli\"	http://www.conservatorionovara.it/",
"CONSERVATORIO di PADOVA \"Cesare Pollini\"	http://www.conservatoriopollini.it",
"CONSERVATORIO di PALERMO \"Vincenzo Bellini\"	http://www.conservatoriobllini.it/",
"CONSERVATORIO di PARMA \"Arrigo Boito\"	http://www.conservatorio.pr.it/",
"CONSERVATORIO di PERUGIA \"Francesco Morlacchi\"	http://www.conservatorioperugia.it",
"CONSERVATORIO di PESARO \"Gioacchino Rossini\"	http://www.conservatoriorossini.it/",
"CONSERVATORIO di PESCARA \"Luisa d'Annunzio\"	http://www.conservatorioluisadannunzio.it",
"CONSERVATORIO di PIACENZA \"Giuseppe Nicolini\"	http://www.conservatorio.piacenza.it",
"CONSERVATORIO di POTENZA \"Gesualdo da Venosa\"	http://www.conservatoriopotenza.it",
"CONSERVATORIO di REGGIO CALABRIA \"Francesco Cilea\"	http://digilander.libero.it/conservatoriocilea/",
"CONSERVATORIO di ROMA \"Santa Cecilia\"	http://www.conservatoriosantacecilia.it",
"CONSERVATORIO di ROVIGO \"Francesco Venezze\"	http://www.conservatoriorovigo.it/",
"CONSERVATORIO di SALERNO \"G. Martucci\"	http://www.consalerno.com",
"CONSERVATORIO di SASSARI \"Luigi Canepa\"	http://www.conservatorio.sassari.it",
"CONSERVATORIO di TORINO \"Giuseppe Verdi\"	http://www.conservatoriotorino.eu/",
"CONSERVATORIO di TRAPANI \"Antonio Scontrino\"	http://www.conservatorio-trapani.it/",
"CONSERVATORIO di TRENTO \"Francesco A. Bonporti\"	http://www.conservatorio.tn.it",
"CONSERVATORIO di TRENTO \"Francesco A. Bonporti\" - sezione staccata	http://www.conservatorio.tn.it/",
"CONSERVATORIO di TRIESTE \"Giuseppe Tartini\"	http://www.conservatorio.trieste.it",
"CONSERVATORIO di UDINE \"Jacopo Tomadini\"	http://www.conservatorio.udine.it/",
"CONSERVATORIO di VENEZIA \"Benedetto Marcello\" - palazzo pisani	http://www.conseve.net/",
"CONSERVATORIO di VERONA \"E. F. dall'Abaco\"	http://www.conservatorioverona.it",
"CONSERVATORIO di VIBO VALENTIA \"Fausto Torrefranca\"	http://www.conservatoriovibovalentia.it",
"CONSERVATORIO di VICENZA \"Arrigo Pedrollo\"	http://www.consvi.org/"

    ]